# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1989dd89c6222007da0eaf2a2f80649a1e9d4890df6fe822837d98bf96cf1b7c52e11c92d9d298024ae9868ac516246ee68fbb1c88330702c338df64cbb930d

test:
  secret_key_base: 028ceb13f2dde547c246929bac5b3e3be5890fcd942be9d3db4f26b9f5166222e9845bd7a87ba348992bdb2c2dea3182eecc147ce9b4ea7b06347815df835888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
